//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcRestaurant.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHAREKET
    {
        public int ID { get; set; }
        public Nullable<int> YEMEK { get; set; }
        public Nullable<int> UYE { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public Nullable<System.DateTime> SIPARISTAH { get; set; }
    
        public virtual TBLUYELER TBLUYELER { get; set; }
        public virtual TBLYEMEK TBLYEMEK { get; set; }
    }
}
